### PR TITLE
Fix workflow

### PR DESCRIPTION
**Pull request by smithdc1**

### CODE REVIEW

**Comment by smithdc1** [comment]
So it works with `virtualenv`. That narrows it down to a conda issue which confirms what is seen in [logs](https://github.com/django/django-asv/actions/runs/4899868050/jobs/8750143900#step:6:12)

**Review by carltongibson — APPROVED** [review]
Looks good. Dropping the summary? (No vibes, just wondering?)

**Comment by smithdc1** [comment]
It's all a bit broken. I'm not sure why 😢 

The workflows have been not working for the past week (or maybe 2 by now). https://github.com/django/django-asv/actions

It seems conda isn't working which we were using to test against multiple pythons. Conda is giving an error message with something like

```
SpecNotFound: /tmp/tmpamp_6v0p.yml is not a valid yaml file.
```

I've managed to cat that file in the runner and I get 

```
runner@fv-az280-798:~/work/django-asv/django-asv$ cat /tmp/tmp0oboqqg_.yml
name: conda-py3.10
channels:
dependencies:
   - python=3.10
   - wheel
   - pip
```


Anyone spot anything wrong with this? 🤷

**Comment by smithdc1** [comment]
So by editing the `.yml` file to:

```
name: conda-py3.10
dependencies:
  - python=3.10
  - wheel
  - pip
```

Conda was able to successfully create the environment.

**Pull request merged**
