### PR TITLE
request response benchmarks added

### PR DESCRIPTION
**Pull request by deepakdinesh1123**
I have added two request-response benchmarks 
- default middleware 
- HTTP methods

### CODE REVIEW

**Comment by carltongibson** [comment]
This looks good @deepakdinesh1123 let me have a play this afternoon 👍

**Review by carltongibson — APPROVED** [review]
@deepakdinesh1123 Do you want to rebase and merge these in? 👍

**Comment by kezabelle** [comment]
I happened to stumble across this in my GH timeline yesterday (hi!), and just wanted to drop a quick note, apologies for barging in.

I don't think it's a _substantial_ issue (and it's certainly better than nothing!) but these two additions (`DefaultMiddleWareBench` and `HttpMethods`) are also implicitly testing the performance characteristics of the `RequestFactory` and `Client` implementations, I think? 
If, for whatever reason, either of those got slower (or faster), there'd potentially be a deviation that looks _more_ positive/negative than it actually is?

**Comment by carltongibson** [comment]
Hey @kezabelle 👋. 

* _"... it's certainly better than nothing!"_ — At this stage, exactly: getting _some_ benchmarks in place is the start point. 
* I'm hoping this will become an ongoing resource, so tweaks welcome. 😉

**Pull request merged**
