### PR TITLE
Pin Miniforge

### PR DESCRIPTION
**Pull request by smithdc1**
While we're waiting for a fix to asv to be compatabile with recent versions of conda let's try and pin to a conda version which works.

### CODE REVIEW

**Comment by smithdc1** [comment]
@sarahboyce what do you think?

**Review by sarahboyce — APPROVED** [review]
Let's do it 👍

**Comment by sarahboyce** [comment]
@smithdc1 do you know if we need to do a similar change in django's benchmark GitHub action?
This doesn't look like it completed properly: https://github.com/django/django/actions/runs/9188334939/job/25267947914?pr=18187 🤔

**Comment by smithdc1** [comment]
Yes. That seems to make sense. I think that's the best option for now.

**Pull request merged**
